### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by farscape11** [sbalci/ClinicoPathJamoviModule#2]
The module doesn't seem to be working on the new Jamovi 1.29. It crashes and doesn't show all the options in the module as well
![image](https://user-images.githubusercontent.com/60532075/76637809-67e6fb00-6519-11ea-8d97-914be18b4a65.png)

**Comment by sbalci** [comment]
Hi,
Not all functions are released yet. It will take some time. Your screenshot shows the current working functions.
Which operating system are you using?
Would you please define how it crashes?
Thank you for the feedback.

Serdar

**Comment by sbalci** [comment]
Please try this new release.
Includes graphs and plots as well.
https://github.com/sbalci/ClinicoPathJamoviModule/releases/download/v0.0.1.0001/ClinicoPath_0.0.1.0001-macos-R3.6.1.jmo

**Comment by farscape11** [comment]
Thanks! Will try.

**Comment by farscape11** [comment]
Windows 10.

It says not enough resources after I put variables in.

**Comment by farscape11** [comment]
It is a macos release so cannot use it on a windows machine.
