### ISSUE TITLE
Problem on Interrater Reliability calculation with meddecide

### ISSUE THREAD

**Issue by GuilhermeCSLima** [sbalci/ClinicoPathJamoviModule#27]
Hello!
First of all, I'm new in the GitHub world so I don't know if this is the right place to put this issue. I'm a Radiologist from Brazil who is taking its first steps in statistics and the use of software to do it. I needed to do some Interrater Reliability calculation using the Cohen's Kappa and was literally searching on google how to do it when I came across with the Jamovi software and the ClinicoPath Module. 

I've installed the submodule "meddecide" to use the Interrater Reliability calculation but I'm facing some problems. When I put the data and try to calculate the Cohen Kappa the following message appears: DLL 'IpSolve' not found: maybe not installed for this architecture?.

Is there something I'm doing wrong? 
Thank you in advance for the help. 

OBS:
I'm using Jamovi Version 1.2.25.0 for Windows

**Comment by sbalci** [comment]
Dear @GuilhermeCSLima 
Thank you for trying the module
The problem may be due to the operating system.
Please download windows version from here: https://github.com/sbalci/ClinicoPath/releases/tag/v0.0.2.0015
This includes interrater reliability as well.

**Comment by sbalci** [comment]
The windows version of meddecide could be downloaded here as well:
https://library.jamovi.org/win64/R3.6.3/meddecide-0.0.1.0005.jmo
Let me know if you have questions.

**Comment by GuilhermeCSLima** [comment]
Hello @sbalci 
Now it works perfectly! Maybe the problem is that I downloaded an old version
Thank you very much!!
