### ISSUE TITLE
`ggstatsplot` next release removes helper message functions

### ISSUE THREAD

**Issue by IndrajeetPatil** [sbalci/ClinicoPathJamoviModule#3]
If I am not mistaken, this module currently uses `normality_message` and `bartlett_message` functions exported from `ggstatsplot`. 

But these functions will be removed in the next release (https://github.com/IndrajeetPatil/ggstatsplot/issues/417)

![image](https://user-images.githubusercontent.com/11330453/80947823-3e4ba100-8df1-11ea-86f1-f05cced30425.png)

If you want to use them, feel free to copy the code from here and implement it internally in this module: 
https://github.com/cran/ipmisc/blob/master/R/helpers_messages.R

**Comment by sbalci** [comment]
Thank you very much for the update @IndrajeetPatil 
Previously I could not implement those functions successfully. But I will try adding internally. But since it is debatable, maybe I should just remove them.

**Comment by sbalci** [comment]
Thank you @IndrajeetPatil. 
Not functioning yet but copied here:
https://github.com/sbalci/ClinicoPathJamoviModule/blob/master/R/jjhelpers_messages.R
