### ISSUE TITLE
(non-English) Character not showing correctly in some Analysis results table

### ISSUE THREAD

**Issue by highwindmx** [sbalci/ClinicoPathJamoviModule#86]
Chinese character seems not show correctly in some table (Multivariable Survival Analysis)
![图片](https://github.com/sbalci/ClinicoPathJamoviModule/assets/6413481/eff20482-9cf7-4e9f-8eb2-2abded92a66c)
![图片](https://github.com/sbalci/ClinicoPathJamoviModule/assets/6413481/05fc5efe-3a83-4c84-9e90-b0a0659f1a61)

**Comment by sbalci** [comment]
Hi,
For multivariable analysis please make sure that the levels in smoking are nominal and not ordinal. The analysis table is not correctly formed.
For the kaplan meier curve please also try deathwatch module of jamovi and see if it works there. 
If it does not work also please contact forum.jamovi.org

**Comment by highwindmx** [comment]
I thought it may be a font/encoding issue? 
can I set Sys.setlocale(category = "LC_ALL", locale = "zh_CN.utf-8") in the script?
